### ISSUE TITLE
[Bug] Micronaut Fails to send email if Hibernate Validator is in Classpath

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-email#259]
### Expected Behavior

Email to be sent

### Actual Behaviour

```
11:28:07.335 [qtp766585947-51] WARN  reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoSuchMethodError: Required method decorate(Builder) not found for class: io.micronaut.email.template.DefaultTemplateBodyDecorator. Most likely cause of this error is the method declaration is not annotated with @Executable. Alternatively check that there is not an unsupported or older version of a dependency present on the classpath. Check your classpath, and ensure the incompatible classes are not present and/or recompile classes as necessary.
	at io.micronaut.core.reflect.ReflectionUtils.newNoSuchMethodError(ReflectionUtils.java:416)
	at io.micronaut.core.reflect.ReflectionUtils.lambda$getRequiredMethod$0(ReflectionUtils.java:240)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.micronaut.core.reflect.ReflectionUtils.getRequiredMethod(ReflectionUtils.java:240)
	at io.micronaut.email.template.$DefaultTemplateBodyDecorator$Definition$Exec.getTargetMethodByIndex(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.getTargetMethod(AbstractExecutableMethodsDefinition.java:401)
	at io.micronaut.aop.chain.MethodInterceptorChain.getTargetMethod(MethodInterceptorChain.java:156)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:96)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.email.template.$DefaultTemplateBodyDecorator$Definition$Intercepted.decorate(Unknown Source)
	at io.micronaut.email.DefaultEmailSender.send(DefaultEmailSender.java:53)
	at io.micronaut.email.$DefaultEmailSender$Definition$Intercepted.$$access$$send(Unknown Source)
	at io.micronaut.email.$DefaultEmailSender$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.validation.ValidatingInterceptor.validateReturnExecutableValidator(ValidatingInterceptor.java:166)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:109)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.email.$DefaultEmailSender$Definition$Intercepted.send(Unknown Source)
```

### Steps To Reproduce

Checkout the Repo and Run the Tests

### Example Application

https://github.com/driverpt/micronaut-email-bug

### Version

4.0.0

**Comment by wetted** [comment]
@driverpt Thank for the bug report. I confirmed it with an independent example. I don't yet have an official solution, but can provide you a workaround I think will work. 

You need to use either `micronaut-hibernate-validator` or `micronaut-validation` dependencies, but not both at the same time. 

1. Remove `implementation("io.micronaut.validation:micronaut-validation")` from your build. 
2. In addition, exclude the transitive dependencies from the Micronaut email modules and the Micronaut hibernate-validator module:
```
    implementation("io.micronaut.email:micronaut-email-amazon-ses"){
        exclude(module = "micronaut-validation")
    }
    implementation("io.micronaut.email:micronaut-email-template") {
        exclude(module = "micronaut-validation")
    }
    implementation("io.micronaut.beanvalidation:micronaut-hibernate-validator"){
        exclude(module = "micronaut-validation")
    }
```

I think this should work in the meantime. It does at least for both your test case and mine.

**Comment by sdelamo** [comment]
@driverpt you applications contains both Micronaut Validation and Micronaut Hibernate Validator. You have to choose. Either use: 


```groovy
 annotationProcessor("io.micronaut.validation:micronaut-validation-processor")
    implementation("io.micronaut.validation:micronaut-validation")
```

or 
```groovy
implementation("io.micronaut.beanvalidation:micronaut-hibernate-validator")
```

**Comment by sdelamo** [comment]
> @driverpt Thank for the bug report. I confirmed it with an independent example. 

where is this independent example? Please, always show reproducible examples.

**Comment by wetted** [comment]
> @wetted
> 
> > I confirmed it with an independent example.
> 
> where is this independent example? Please, always show reproducible examples.

I can duplicate it with the [OCI/Email guide](https://guides.micronaut.io/latest/micronaut-oracle-email-delivery-gradle-java.html). Using the solution, if I comment out `
implementation("io.micronaut.validation:micronaut-validation")` and use `implementation("io.micronaut.beanvalidation:micronaut-hibernate-validator")` 
instead it fails with the same error as the report.
